// This file is autogenerated. Do not modify.

namespace CBSDB {

std::string sql_str_insert_into_executions(struct executions& s) {
std::stringstream sql;
sql << "insert into executions ("
<< "pb_name,"
<< "num_ex,"
<< "branching_name"
<< ") values ("
<< "'" << s.pb_name << "'" << ","
<< s.num_ex << ","
<< "'" << s.branching_name << "'" << ");";
return sql.str();
}
std::string sql_str_insert_into_results(struct results& s) {
std::stringstream sql;
sql << "insert into results ("
<< "exec_id,"
<< "var_id,"
<< "val"
<< ") values ("
<< s.exec_id << ","
<< s.var_id << ","
<< s.val << ");";
return sql.str();
}
std::string sql_str_insert_into_nodes(struct nodes& s) {
std::stringstream sql;
sql << "insert into nodes ("
<< "exec_id,"
<< "node_id"
<< ") values ("
<< s.exec_id << ","
<< s.node_id << ");";
return sql.str();
}
std::string sql_str_insert_into_propagators(struct propagators& s) {
std::stringstream sql;
sql << "insert into propagators ("
<< "exec_id,"
<< "node_id,"
<< "prop_id"
<< ") values ("
<< s.exec_id << ","
<< s.node_id << ","
<< s.prop_id << ");";
return sql.str();
}
std::string sql_str_insert_into_densities(struct densities& s) {
std::stringstream sql;
sql << "insert into densities ("
<< "exec_id,"
<< "node_id,"
<< "var_id,"
<< "val,"
<< "max_sd,"
<< "a_avg_sd,"
<< "var_dom_size,"
<< "max_rel_sd,"
<< "max_rel_ratio"
<< ") values ("
<< s.exec_id << ","
<< s.node_id << ","
<< s.var_id << ","
<< s.val << ","
<< s.max_sd << ","
<< s.a_avg_sd << ","
<< s.var_dom_size << ","
<< s.max_rel_sd << ","
<< s.max_rel_ratio << ");";
return sql.str();
}
}
