#!/usr/bin/env zsh

cd "$(dirname "$0")"

def="__SQL_STRUCTS_HH__"
file="sql-structs.hh"

echo """// This file is autogenerated. Do not modify.

#ifndef $def
#define $def

namespace CBSDB {
""" > $file

awk '
BEGIN   {
    type["uint"]="unsigned int"
    type["int"]="int"
    type["double"]="double"
    type["str"]="std::string"
}

/^TABLE /   { print "  struct " $2 " {" }

/^C |^LC /  { print "    " type[$3] " " $2 ";"}

/^END /     { print "  };\n"; }
' <<< $(cat ../schema.txt | grep -v "^//") >> $file


echo """
}

#endif //end $def
""" >> $file
