// This file is autogenerated. Do not modify.

#ifndef __SQL_STRUCTS_HH__
#define __SQL_STRUCTS_HH__

namespace CBSDB {

  struct executions {
    std::string pb_name;
    unsigned int num_ex;
    std::string branching_name;
    std::string path_db;
  };

  struct results {
    unsigned int exec_id;
    unsigned int var_id;
    int val;
  };

  struct nodes {
    unsigned int exec_id;
    unsigned int node_id;
  };

  struct propagators {
    unsigned int exec_id;
    unsigned int node_id;
    unsigned int prop_id;
  };

  struct densities {
    unsigned int exec_id;
    unsigned int node_id;
    unsigned int var_id;
    int val;
    double max_sd;
    double a_avg_sd;
    unsigned int var_dom_size;
    double max_rel_sd;
    double max_rel_ratio;
  };


}

#endif //end __SQL_STRUCTS_HH__

