#!/usr/bin/env zsh

cd "$(dirname "$0")"

strs=$(cat ../schema.txt | grep " str$" | cut -d' ' -f1)

file="sql-str-query.hpp"

echo """// This file is autogenerated

namespace CBSDB {
""" > $file

cpp_vars=""
while read line; do
    case $line in
        TABLE*)
            table_name=$(echo $line | cut -d" " -f2)
            echo "std::string sql_str_insert_into_$table_name(struct $table_name& s) {"
            echo "std::stringstream sql;"
            echo "sql"
            echo '<< "insert into '$table_name' ("'
            ;;
        \#END*)
            echo '<< ") values ("'
            echo -n $cpp_vars
            cpp_vars=""
            echo '<< ");";'
            echo "return str.str();"
            echo "}"
            echo
            ;;
        *" "*)
            var_name=$(echo $line | cut -d" " -f1)
            var_type=$(echo $line | cut -d" " -f2)
            echo '<< "'$var_name'," '
            if [ "$(echo $strs | grep $var_name)" != "" ]; then
                cpp_vars+="<< \"'\" << s.$var_name << \"',\"\n"
            else
                cpp_vars+='<< s.'$var_name' << ", "\n'
            fi;
            ;;
    esac
done <<< $(cat ../schema.txt | grep -v "#SQL") >> $file

echo "}" >> $file
