#!/usr/bin/env zsh

cd "$(dirname "$0")"

typeset -A types
types[uint]="unsigned int"
types[int]="int"
types[double]="double"
types[str]="std::string"

def="__SQL_STRUCTS_HH__"
file="sql-structs.hh"

echo """// This file is autogenerated

#ifndef $def
#define $def

namespace CBSDB {
""" > $file

while read line; do
    echo -n " "
    case $line in
        TABLE*)
            table_name=$(echo $line | cut -d" " -f2)
            echo struct $table_name {
            ;;
        \#END*)
            echo }\;
            ;;
        *" "*)
            var_name=$(echo $line | cut -d" " -f1)
            var_type=$(echo $line | cut -d" " -f2)
            echo -n "  "
            echo ${types[$var_type]} $var_name\;
            ;;
        "")
            echo
            ;;
    esac
done <<< $(cat ../schema.txt | grep -v "#SQL") >> $file

echo """
}

#endif //end $def
""" >> $file
