#!/usr/bin/env zsh

cd "$(dirname "$0")"

file="sql-str-query.hpp"

echo """// This file is autogenerated. Do not modify.

namespace CBSDB {
""" > $file

awk '
/^TABLE/ {
    cpp=""
    print "std::string sql_str_insert_into_" $2 "(const struct " $2 "&& s) {" 
    print "std::stringstream sql;"
    print "sql << \"insert into " $2 " (\""
}

/^L?C /  { 
    printf "<< \"" $2 

    if ($3 == "str") { cpp=cpp "<< \"'\''\" " }
    cpp=cpp "<< s." $2
    if ($3 == "str") { cpp=cpp " << \"'\''\"" }
}
/^C /    { 
    printf ",\""
    cpp=cpp " << \",\"\n"
}

/^LC /   { 
    printf "\"" 
}

/^L?C /  { 
    printf "\n"
}
/END/   {
    print "<< \") values (\""
    printf cpp
    print " << \");\";"
    print "return sql.str();"
    print "}"
}
' <<< $(cat ../schema.txt | grep -v "^//") >> $file

echo  "}" >> $file

